var historyLog = [
    "bhstdmngbgr02/Acceptance_test",
    "bhstdmngbgr03/Acceptance_test",
    "bhstdmngbgr04/Acceptance_test",
    "bhstdmngbgr05/Acceptance_test",
    "bhstdmngbgr06/Acceptance_test",
    "bhstdmngbgr07/Acceptance_test",
    "bhstdmngbgr08/Acceptance_test",
    "bhstdmngbgr09/Acceptance_test",
    "bhstdmngbgr10/Acceptance_test",
    "bhstdmngbgr11/Acceptance_test",
    "bhstdmngbgr12/Acceptance_test",
    "bhstdmngbgr13/Acceptance_test"
];
var machines = [
    {
        dns:"bjstdmngr01.throughtworks.com",
        status:"idle",
        ip:"192.168.1.102",
        folder:"/var/lib/cruise-agent",
        browsers:[
            "Firefox",
            "Safari",
            "Ubuntu",
            "Chrome"
        ],
        operatingSystem:"windows",
        denyOrNo:"no"
    },
    {
        dns:"bjstdmngr08.throughtworks.com",
        status:"building",
        ip:"192.168.1.243",
        folder:"/var/lib/cruise-agent",
        browsers:[
            "Firefox",
            "Safari",
            "Ubuntu",
            "Chrome"
        ],
        operatingSystem:"windows",
        denyOrNo:"yes"
    },
    {
        dns:"bjstdmngr10.throughtworks.com",
        status:"idle",
        ip:"192.168.1.80",
        folder:"/var/lib/cruise-agent",
        browsers:[
            "Firefox",
            "Safari"
        ],
        operatingSystem:"Ubuntu",
        denyOrNo:"yes"
    },
    {
        dns:"bjstdmngr11.throughtworks.com",
        status:"idle",
        ip:"192.168.1.102",
        folder:"/var/lib/cruise-agent",
        browsers:[
            "Firefox",
            "Safari",
            "Ubuntu",
            "Chrome"
        ],
        operatingSystem:"debin",
        denyOrNo:"yes"
    },
    {
        dns:"bjstdmngr15.throughtworks.com",
        status:"idle",
        ip:"192.168.1.102",
        folder:"/var/lib/cruise-agent",
        browsers:[
            "Firefox",
            "Safari",
            "Ubuntu",
            "Chrome"
        ],
        operatingSystem:"suse",
        denyOrNo:"no"
    },
    {
        dns:"bjstdmngr16.throughtworks.com",
        status:"idle",
        ip:"192.168.1.102",
        folder:"/var/lib/cruise-agent",
        browsers:[
            "Firefox",
            "Safari",
            "Ubuntu",
            "Chrome"
        ],
        operatingSystem:"cent",
        denyOrNo:"no"
    }
];